function openBanglishModal(){setActiveMode("mode-banglish");document.getElementById("banglishModal").style.display="flex";document.body.style.overflow="hidden"}
function closeBanglishModal(){document.getElementById("banglishModal").style.display="none";document.body.style.overflow="auto";document.getElementById("bnInput").value="";document.getElementById("banglishOutput").innerText="Your result will appear here..."}
function convertToBanglish(){const input=document.getElementById("bnInput").value;if(!input){document.getElementById("banglishOutput").innerText="Your result will appear here...";return}
const mapping={'অ':'o','আ':'a','ই':'i','ঈ':'i','উ':'u','ঊ':'u','ঋ':'ri','এ':'e','ঐ':'oi','ও':'o','ঔ':'ou','া':'a','ি':'i','ী':'i','ু':'u','ূ':'u','ৃ':'ri','ে':'e','ৈ':'oi','ো':'o','ৌ':'ou','ক':'k','খ':'kh','গ':'g','ঘ':'gh','ঙ':'ng','চ':'ch','ছ':'ch','জ':'j','ঝ':'jh','ঞ':'n','ট':'t','ঠ':'th','ড':'d','ঢ':'dh','ণ':'n','ত':'t','থ':'th','দ':'d','ধ':'dh','ন':'n','প':'p','ফ':'f','ব':'b','ভ':'v','ম':'m','য':'j','র':'r','ল':'l','শ':'s','ষ':'s','স':'s','হ':'h','ড়':'r','ঢ়':'r','য়':'y','ৎ':'t','ং':'ng','ঃ':'h','ঁ':'','।':'.','্':'','়':''};const yaPhala="্য";const consonants="কখগঘঙচছজঝঞটঠডঢণতথদধনপফবভমযরলশষসহড়ঢ়য়";let output="";let i=0;while(i<input.length){let char=input[i];let nextChar=input[i+1];if(char==='য'&&nextChar==='়'){output+="y";i+=2;continue}
if(nextChar===yaPhala){let base=mapping[char]||"";if(!input[i+2]||input[i+2]===" "||input[i+2]==="।"){output+=base+base+"o";i+=2;continue}else{output+=base+"ya";i+=2;continue}}
if(mapping[char]!==undefined){output+=mapping[char];if(consonants.includes(char)&&nextChar&&consonants.includes(nextChar)){if(char==='ল'||char==='ন'||char==='জ'){output+="o"}}}else{output+=char}
i++}
let finalOutput=output.replace(/aa/g,'a').replace(/ii/g,'i').replace(/uu/g,'u').replace(/oo/g,'o').replace(/jnj/g,'jonno').replace(/valbasi/g,'valobasi').replace(/tomaj/g,'tomay').replace(/bajaj/g,'bajay');if(finalOutput.length>0){finalOutput=finalOutput.charAt(0).toUpperCase()+finalOutput.slice(1).toLowerCase()}
document.getElementById("banglishOutput").innerText=finalOutput}
function copyBanglishText(){const text=document.getElementById("banglishOutput").innerText;const btn=document.getElementById("btnCopyBanglish");if(text==="Your result will appear here..."||!text)return;navigator.clipboard.writeText(text).then(()=>{const oldHtml=btn.innerHTML;btn.style.background="#10b981";btn.innerHTML="<i class='fa-solid fa-check'></i> Copied!";setTimeout(()=>{btn.innerHTML=oldHtml;btn.style.background="#059669"},2000)})}
