let sigSourceCanvas,sigSourceCtx,sigCanvas,sigCtx;let sigRawImg=null,sigInkColor="original";let isSigCropMode=!1,sigIsDragging=!1,sigIsResizing=!1;let sigActiveHandle=null,sigStartX,sigStartY;let sCropX=0,sCropY=0,sCropW=0,sCropH=0;let isEraserMode=!1,isErasing=!1;let eraserSize=20,sigZoomScale=1;let isPanning=!1,panX=0,panY=0,startPanX=0,startPanY=0;function openSigRemoverModal(){setActiveMode("mode-sig-remover");document.getElementById("sigRemoverModal").style.display="flex";document.body.style.overflow="hidden";sigCanvas=document.getElementById("sigCanvas");sigCtx=sigCanvas.getContext("2d",{willReadFrequently:!0});sigSourceCanvas=document.getElementById("sigSourceCanvas");sigSourceCtx=sigSourceCanvas.getContext("2d",{willReadFrequently:!0});initEraserEvents();initPanningEvents()}
function closeSigRemoverModal(){document.getElementById("sigRemoverModal").style.display="none";document.body.style.overflow="auto";resetSigTool()}
function updateCanvasTransform(){sigCanvas.style.transform=`translate(${panX}px, ${panY}px) scale(${sigZoomScale})`}
function resetSigTool(){sigRawImg=null;sigZoomScale=1;panX=0;panY=0;document.getElementById("sigInput").value="";document.getElementById("sigPlaceholder").style.display="block";document.getElementById("sigZoomWrapper").style.display="none";sigCanvas.style.display="none";updateCanvasTransform();document.getElementById("v-sigZoom").innerText="100%";document.getElementById("sigUploadArea").classList.remove("has-img");document.getElementById("sigThreshold").value=150;document.getElementById("v-sigThreshold").innerText=150;document.getElementById("sigSmooth").value=0;document.getElementById("v-sigSmooth").innerText=0;sigInkColor="original";document.querySelectorAll('.sig-color-item').forEach(i=>i.classList.remove('active'));document.querySelector('.sig-color-item[title="Original Color"]').classList.add('active');isEraserMode=!1;document.getElementById("sigEraserBtn").classList.remove("active","eraser-active-blink");document.getElementById("eraserCursor").style.display="none";document.getElementById("sigCropBox").style.display="none";document.getElementById("sigCropControls").style.display="none";isSigCropMode=!1}
document.getElementById("sigInput").onchange=function(e){const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=function(event){const img=new Image();img.onload=function(){sigRawImg=img;sigSourceCanvas.width=img.width;sigSourceCanvas.height=img.height;sigSourceCtx.drawImage(img,0,0);sigCanvas.style.display="block";document.getElementById("sigPlaceholder").style.display="none";document.getElementById("sigZoomWrapper").style.display="flex";document.getElementById("sigUploadArea").classList.add("has-img");processSignature()};img.src=event.target.result};reader.readAsDataURL(file)};function processSignature(){if(!sigRawImg)return;if(sigCanvas.width!==sigSourceCanvas.width){sigCanvas.width=sigSourceCanvas.width;sigCanvas.height=sigSourceCanvas.height}
const threshold=parseInt(document.getElementById("sigThreshold").value);const smooth=parseInt(document.getElementById("sigSmooth").value);const imgData=sigSourceCtx.getImageData(0,0,sigSourceCanvas.width,sigSourceCanvas.height);const data=imgData.data;const isOriginal=(sigInkColor==="original");let rInk,gInk,bInk;if(!isOriginal){rInk=parseInt(sigInkColor.slice(1,3),16);gInk=parseInt(sigInkColor.slice(3,5),16);bInk=parseInt(sigInkColor.slice(5,7),16)}
for(let i=0;i<data.length;i+=4){if(data[i+3]===0)continue;const brightness=(data[i]*0.299+data[i+1]*0.587+data[i+2]*0.114);if(brightness>threshold){data[i+3]=0}else{if(!isOriginal){data[i]=rInk;data[i+1]=gInk;data[i+2]=bInk}
if(smooth>0&&brightness>(threshold-40)){data[i+3]=Math.min(255,(threshold-brightness)*(11-smooth))}}}
sigCtx.putImageData(imgData,0,0)}
function initEraserEvents(){const cursor=document.getElementById("eraserCursor");const container=document.getElementById("sigUploadArea");const getCoords=(e)=>{const rect=sigCanvas.getBoundingClientRect();const clientX=e.touches?e.touches[0].clientX:e.clientX;const clientY=e.touches?e.touches[0].clientY:e.clientY;return{x:(clientX-rect.left)*(sigCanvas.width/rect.width),y:(clientY-rect.top)*(sigCanvas.height/rect.height),rawX:clientX-container.getBoundingClientRect().left,rawY:clientY-container.getBoundingClientRect().top}};const handlePointer=(e)=>{if(!isEraserMode||!sigRawImg)return;const pos=getCoords(e);cursor.style.display='block';cursor.style.width=eraserSize+'px';cursor.style.height=eraserSize+'px';cursor.style.left=(pos.rawX-eraserSize/2)+'px';cursor.style.top=(pos.rawY-eraserSize/2)+'px';if(isErasing){const rad=(eraserSize/2)*(sigCanvas.width/sigCanvas.getBoundingClientRect().width);sigCtx.globalCompositeOperation='destination-out';sigCtx.beginPath();sigCtx.arc(pos.x,pos.y,rad,0,Math.PI*2);sigCtx.fill();sigSourceCtx.globalCompositeOperation='destination-out';sigSourceCtx.beginPath();sigSourceCtx.arc(pos.x,pos.y,rad,0,Math.PI*2);sigSourceCtx.fill()}};sigCanvas.addEventListener('mousedown',(e)=>{if(isEraserMode)isErasing=!0;handlePointer(e)});window.addEventListener('mousemove',handlePointer);window.addEventListener('mouseup',()=>{if(isErasing){isErasing=!1;sigCtx.globalCompositeOperation='source-over';sigSourceCtx.globalCompositeOperation='source-over'}});sigCanvas.addEventListener('touchstart',(e)=>{if(isEraserMode)isErasing=!0;handlePointer(e)});window.addEventListener('touchmove',handlePointer);window.addEventListener('touchend',()=>{isErasing=!1});container.addEventListener('mouseleave',()=>cursor.style.display='none')}
function applySigCrop(){const rect=sigCanvas.getBoundingClientRect();const scaleX=sigCanvas.width/rect.width,scaleY=sigCanvas.height/rect.height;const tempCanvas=document.createElement('canvas');tempCanvas.width=sCropW*scaleX;tempCanvas.height=sCropH*scaleY;const tCtx=tempCanvas.getContext('2d');tCtx.drawImage(sigSourceCanvas,sCropX*scaleX,sCropY*scaleY,sCropW*scaleX,sCropH*scaleY,0,0,tempCanvas.width,tempCanvas.height);sigSourceCanvas.width=tempCanvas.width;sigSourceCanvas.height=tempCanvas.height;sigSourceCtx.clearRect(0,0,sigSourceCanvas.width,sigSourceCanvas.height);sigSourceCtx.drawImage(tempCanvas,0,0);toggleSigCrop();processSignature()}
document.getElementById("sigThreshold").oninput=(e)=>{document.getElementById("v-sigThreshold").innerText=e.target.value;processSignature()};document.getElementById("sigSmooth").oninput=(e)=>{document.getElementById("v-sigSmooth").innerText=e.target.value;processSignature()};document.getElementById("sigEraserSize").oninput=(e)=>{eraserSize=parseInt(e.target.value);document.getElementById("v-sigEraserSize").innerText=eraserSize};function setInkColor(color,el){sigInkColor=color;document.querySelectorAll('.sig-color-item').forEach(i=>i.classList.remove('active'));if(el)el.classList.add('active');processSignature()}
function changeSigZoom(delta){if(!sigRawImg)return;sigZoomScale=Math.min(4,Math.max(1,sigZoomScale+delta));if(sigZoomScale===1){panX=0;panY=0}
updateCanvasTransform();document.getElementById("v-sigZoom").innerText=Math.round(sigZoomScale*100)+"%"}
function initPanningEvents(){const startPan=(e)=>{if(!sigRawImg||isEraserMode||isSigCropMode)return;isPanning=!0;const pos=e.touches?e.touches[0]:e;startPanX=pos.clientX-panX;startPanY=pos.clientY-panY;sigCanvas.style.transition="none"};const doPan=(e)=>{if(!isPanning)return;const pos=e.touches?e.touches[0]:e;panX=pos.clientX-startPanX;panY=pos.clientY-startPanY;updateCanvasTransform()};const stopPan=()=>{isPanning=!1;if(sigCanvas)sigCanvas.style.transition="transform 0.05s linear"};sigCanvas.addEventListener('mousedown',startPan);window.addEventListener('mousemove',doPan);window.addEventListener('mouseup',stopPan);sigCanvas.addEventListener('touchstart',startPan);window.addEventListener('touchmove',doPan);window.addEventListener('touchend',stopPan)}
function toggleSigEraser(){if(!sigRawImg)return;isEraserMode=!isEraserMode;const b=document.getElementById("sigEraserBtn");if(isEraserMode){b.classList.add("active","eraser-active-blink");sigCanvas.style.cursor="none";if(isSigCropMode)toggleSigCrop();}else{b.classList.remove("active","eraser-active-blink");sigCanvas.style.cursor="grab"}}
function toggleSigCrop(){if(!sigRawImg)return;if(sigZoomScale>1){sigZoomScale=1;panX=0;panY=0;updateCanvasTransform();document.getElementById("v-sigZoom").innerText="100%"}
isSigCropMode=!isSigCropMode;const cBox=document.getElementById("sigCropBox"),cCtrl=document.getElementById("sigCropControls");if(isSigCropMode){if(isEraserMode)toggleSigEraser();cBox.style.display="block";cCtrl.style.display="flex";const rect=sigCanvas.getBoundingClientRect();sCropW=rect.width*0.7;sCropH=rect.height*0.5;sCropX=(rect.width-sCropW)/2;sCropY=(rect.height-sCropH)/2;updateSigCropUI()}else{cBox.style.display="none";cCtrl.style.display="none"}}
function updateSigCropUI(){const cBox=document.getElementById("sigCropBox"),area=document.getElementById("sigUploadArea").getBoundingClientRect(),rect=sigCanvas.getBoundingClientRect();cBox.style.left=(rect.left-area.left+sCropX)+"px";cBox.style.top=(rect.top-area.top+sCropY)+"px";cBox.style.width=sCropW+"px";cBox.style.height=sCropH+"px"}
function initSigResize(e,h){e.stopPropagation();e.preventDefault();sigIsResizing=!0;sigActiveHandle=h;const p=e.touches?e.touches[0]:e;sigStartX=p.clientX;sigStartY=p.clientY}
document.getElementById("sigCropBox").onmousedown=document.getElementById("sigCropBox").ontouchstart=(e)=>{if(e.target.id!=="sigCropBox"||isEraserMode)return;sigIsDragging=!0;const p=e.touches?e.touches[0]:e;sigStartX=p.clientX;sigStartY=p.clientY};window.addEventListener('mousemove',(e)=>{if(!isSigCropMode||(!sigIsDragging&&!sigIsResizing))return;const p=e.touches?e.touches[0]:e;const dx=p.clientX-sigStartX,dy=p.clientY-sigStartY;const rect=sigCanvas.getBoundingClientRect();if(sigIsDragging){sCropX=Math.max(0,Math.min(rect.width-sCropW,sCropX+dx));sCropY=Math.max(0,Math.min(rect.height-sCropH,sCropY+dy))}else if(sigIsResizing){if(sigActiveHandle.includes('r'))sCropW=Math.max(30,Math.min(rect.width-sCropX,sCropW+dx));if(sigActiveHandle.includes('b'))sCropH=Math.max(20,Math.min(rect.height-sCropY,sCropH+dy));if(sigActiveHandle.includes('l')){let nW=Math.max(30,sCropW-dx);if(sCropX+(sCropW-nW)>=0){sCropX+=(sCropW-nW);sCropW=nW}}
if(sigActiveHandle.includes('t')){let nH=Math.max(20,sCropH-dy);if(sCropY+(sCropH-nH)>=0){sCropY+=(sCropH-nH);sCropH=nH}}}
sigStartX=p.clientX;sigStartY=p.clientY;updateSigCropUI()});window.addEventListener('mouseup',()=>{sigIsDragging=!1;sigIsResizing=!1});window.addEventListener('touchend',()=>{sigIsDragging=!1;sigIsResizing=!1});function downloadSignature(){if(!sigRawImg)return;const link=document.createElement('a');link.download="Signature_Pro.png";link.href=sigCanvas.toDataURL("image/png");link.click()}
